-- Banco de histórias
create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  cover_url text default '',
  content text not null,
  created_at timestamptz default now()
);

alter table public.stories enable row level security;

-- Qualquer pessoa pode ler histórias.
drop policy if exists "Public can read stories" on public.stories;
create policy "Public can read stories"
on public.stories for select
using (true);

-- Qualquer pessoa pode publicar uma história.
drop policy if exists "Anyone can insert stories" on public.stories;
create policy "Anyone can insert stories"
on public.stories for insert
with check (true);

-- Edição/exclusão continuam bloqueadas para visitantes.
drop policy if exists "Authenticated can update stories" on public.stories;
create policy "Authenticated can update stories"
on public.stories for update
using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can delete stories" on public.stories;
create policy "Authenticated can delete stories"
on public.stories for delete
using (auth.role() = 'authenticated');
